// SKU Funnel Goals API
// GET, POST, PUT для управления целями по воронке

import { NextResponse } from 'next/server';
import { SKUFunnelGoal, SKUGoalProgress, BulkGoalsUpdate, SKUGoalsFilter, SKUGoalsStats } from '@/types/sku-goals';
import { classifySKUs, getClassBenchmarks } from '@/lib/sku-classifier';
import { getCategoryConfigs } from '@/lib/optimizer/config-manager';
import { getCurrentPeriod } from '@/types/goal-types';

// In-memory storage (TODO: migrate to Supabase)
let goalsStore: Map<string, SKUFunnelGoal> = new Map();

// Generate goal ID
function getGoalId(nmId: number, month: number, year: number): string {
    return `${nmId}_${year}_${month}`;
}

// GET - Получить цели
export async function GET(request: Request) {
    try {
        const { searchParams } = new URL(request.url);

        const nmId = searchParams.get('nmId');
        const categoryId = searchParams.get('categoryId');
        const month = parseInt(searchParams.get('month') || String(getCurrentPeriod().month));
        const year = parseInt(searchParams.get('year') || String(getCurrentPeriod().year));
        const includeProgress = searchParams.get('includeProgress') === 'true';

        // Если запрошен конкретный SKU
        if (nmId) {
            const goalId = getGoalId(parseInt(nmId), month, year);
            const goal = goalsStore.get(goalId);

            return NextResponse.json({
                success: true,
                goal: goal || null,
            });
        }

        // Вернуть все цели (с фильтрацией)
        const allGoals = [...goalsStore.values()].filter(g => {
            if (g.period.month !== month || g.period.year !== year) return false;
            if (categoryId && g.categoryId !== categoryId) return false;
            return true;
        });

        // Статистика
        const stats: SKUGoalsStats = {
            total: allGoals.length,
            byClass: { gold: 0, silver: 0, bronze: 0, new: 0 },
            byStatus: { exceeds: 0, onTrack: 0, atRisk: 0, behind: 0 },
            avgProgress: { ctr: 0, crCart: 0, crOrder: 0 },
        };

        for (const goal of allGoals) {
            stats.byClass[goal.skuClass]++;
        }

        return NextResponse.json({
            success: true,
            goals: allGoals,
            stats,
            period: { month, year },
        });

    } catch (error) {
        console.error('SKU Goals API Error:', error);
        return NextResponse.json(
            { success: false, error: String(error) },
            { status: 500 }
        );
    }
}

// POST - Создать/обновить цели
export async function POST(request: Request) {
    try {
        const body = await request.json();

        // Автогенерация целей
        if (body.action === 'auto-generate') {
            const { skuData, period = getCurrentPeriod() } = body;

            if (!skuData || !Array.isArray(skuData)) {
                return NextResponse.json(
                    { success: false, error: 'skuData array required' },
                    { status: 400 }
                );
            }

            // Классифицировать SKU
            const classifications = classifySKUs(skuData);
            const categoryConfigs = await getCategoryConfigs();

            const generatedGoals: SKUFunnelGoal[] = [];

            for (const sku of skuData) {
                const classification = classifications.get(sku.nmId);
                if (!classification) continue;

                // Получить бенчмарки для класса и категории
                const categoryConfig = categoryConfigs[sku.category?.toLowerCase() || ''];
                const classBenchmarks = categoryConfig?.class_benchmarks;
                const benchmarks = getClassBenchmarks(classification.skuClass, classBenchmarks);

                const goal: SKUFunnelGoal = {
                    nmId: sku.nmId,
                    sku: sku.sku || String(sku.nmId),
                    title: sku.title,
                    categoryId: sku.category as any,
                    skuClass: classification.skuClass,
                    targetCTR: benchmarks.ctr,
                    targetCRCart: benchmarks.crCart,
                    targetCROrder: benchmarks.crOrder,
                    period,
                    isAutoGenerated: true,
                    updatedAt: new Date().toISOString(),
                };

                const goalId = getGoalId(sku.nmId, period.month, period.year);
                goalsStore.set(goalId, goal);
                generatedGoals.push(goal);
            }

            return NextResponse.json({
                success: true,
                generated: generatedGoals.length,
                goals: generatedGoals,
            });
        }

        // Массовое обновление
        if (body.action === 'bulk-update') {
            const { nmIds, goals, period = getCurrentPeriod() }: BulkGoalsUpdate = body;

            if (!nmIds || !Array.isArray(nmIds) || nmIds.length === 0) {
                return NextResponse.json(
                    { success: false, error: 'nmIds array required' },
                    { status: 400 }
                );
            }

            const updated: number[] = [];

            for (const nmId of nmIds) {
                const goalId = getGoalId(nmId, period.month, period.year);
                const existing = goalsStore.get(goalId);

                if (existing) {
                    // Обновить существующую цель
                    const updatedGoal: SKUFunnelGoal = {
                        ...existing,
                        ...goals,
                        isAutoGenerated: false,
                        updatedAt: new Date().toISOString(),
                    };
                    goalsStore.set(goalId, updatedGoal);
                    updated.push(nmId);
                }
            }

            return NextResponse.json({
                success: true,
                updated: updated.length,
                nmIds: updated,
            });
        }

        // Создать/обновить одну цель
        const goal: SKUFunnelGoal = body.goal;

        if (!goal || !goal.nmId) {
            return NextResponse.json(
                { success: false, error: 'goal object with nmId required' },
                { status: 400 }
            );
        }

        const period = goal.period || getCurrentPeriod();
        const goalId = getGoalId(goal.nmId, period.month, period.year);

        goalsStore.set(goalId, {
            ...goal,
            period,
            isAutoGenerated: false,
            updatedAt: new Date().toISOString(),
        });

        return NextResponse.json({
            success: true,
            goal: goalsStore.get(goalId),
        });

    } catch (error) {
        console.error('SKU Goals API Error:', error);
        return NextResponse.json(
            { success: false, error: String(error) },
            { status: 500 }
        );
    }
}

// DELETE - Удалить цели
export async function DELETE(request: Request) {
    try {
        const { searchParams } = new URL(request.url);

        const nmId = searchParams.get('nmId');
        const month = parseInt(searchParams.get('month') || String(getCurrentPeriod().month));
        const year = parseInt(searchParams.get('year') || String(getCurrentPeriod().year));

        if (nmId) {
            const goalId = getGoalId(parseInt(nmId), month, year);
            const deleted = goalsStore.delete(goalId);

            return NextResponse.json({
                success: true,
                deleted,
            });
        }

        // Удалить все цели за период
        const deleteAll = searchParams.get('all') === 'true';
        if (deleteAll) {
            let deletedCount = 0;
            for (const [key, goal] of goalsStore) {
                if (goal.period.month === month && goal.period.year === year) {
                    goalsStore.delete(key);
                    deletedCount++;
                }
            }

            return NextResponse.json({
                success: true,
                deleted: deletedCount,
            });
        }

        return NextResponse.json(
            { success: false, error: 'nmId or all=true required' },
            { status: 400 }
        );

    } catch (error) {
        console.error('SKU Goals API Error:', error);
        return NextResponse.json(
            { success: false, error: String(error) },
            { status: 500 }
        );
    }
}
