// SKU Funnel Goals Types
// Система целей по воронке для каждого товара

import { Category } from '@/lib/auth-types';
import { GoalPeriod } from '@/types/goal-types';

// Класс SKU по выручке
export type SKUClass = 'gold' | 'silver' | 'bronze' | 'new';

// Названия классов для UI
export const SKU_CLASS_LABELS: Record<SKUClass, string> = {
    gold: '🥇 Gold',
    silver: '🥈 Silver',
    bronze: '🥉 Bronze',
    new: '🆕 New',
};

// Цвета для UI
export const SKU_CLASS_COLORS: Record<SKUClass, { bg: string; text: string; border: string }> = {
    gold: { bg: 'bg-yellow-500/20', text: 'text-yellow-400', border: 'border-yellow-500/50' },
    silver: { bg: 'bg-slate-400/20', text: 'text-slate-300', border: 'border-slate-400/50' },
    bronze: { bg: 'bg-orange-600/20', text: 'text-orange-400', border: 'border-orange-500/50' },
    new: { bg: 'bg-blue-500/20', text: 'text-blue-400', border: 'border-blue-500/50' },
};

// Бенчмарки по классам (default, могут быть переопределены в category.yaml)
export const DEFAULT_CLASS_BENCHMARKS: Record<SKUClass, {
    ctr: number;
    crCart: number;
    crOrder: number;
}> = {
    gold: { ctr: 8, crCart: 55, crOrder: 75 },
    silver: { ctr: 6, crCart: 45, crOrder: 65 },
    bronze: { ctr: 4, crCart: 35, crOrder: 55 },
    new: { ctr: 5, crCart: 40, crOrder: 60 }, // Стартовые цели для новинок
};

// Цели по воронке для одного SKU
export interface SKUFunnelGoal {
    id?: string;          // UUID из Supabase
    nmId: number;
    sku: string;
    title?: string;
    categoryId: Category;
    skuClass: SKUClass;

    // Цели (%)
    targetCTR: number;        // % добавлений в корзину от просмотров
    targetCRCart: number;     // % заказов от добавлений в корзину
    targetCROrder: number;    // % выкупов от заказов
    targetRevenue?: number;   // ₽ в месяц (опционально)

    // Период
    period: GoalPeriod;

    // Мета
    isAutoGenerated: boolean;
    createdAt?: string;
    updatedAt?: string;
}

// Прогресс выполнения целей SKU
export interface SKUGoalProgress {
    nmId: number;
    sku: string;
    title: string;
    categoryId: Category;
    skuClass: SKUClass;

    // Цели
    targetCTR: number;
    targetCRCart: number;
    targetCROrder: number;
    targetRevenue?: number;

    // Факт
    actualCTR: number;
    actualCRCart: number;
    actualCROrder: number;
    actualRevenue: number;

    // Прогресс (%)
    ctrProgress: number;      // actualCTR / targetCTR * 100
    crCartProgress: number;
    crOrderProgress: number;
    revenueProgress?: number;

    // Статус
    status: 'exceeds' | 'on_track' | 'at_risk' | 'behind';
    issueCount: number;       // Сколько метрик ниже цели
}

// Результат классификации SKU
export interface SKUClassification {
    nmId: number;
    sku: string;
    skuClass: SKUClass;
    revenue30d: number;
    percentile: number;       // 0-100, позиция в рейтинге выручки
}

// Запрос на массовое обновление целей
export interface BulkGoalsUpdate {
    nmIds: number[];
    goals: Partial<Pick<SKUFunnelGoal, 'targetCTR' | 'targetCRCart' | 'targetCROrder' | 'targetRevenue'>>;
    period: GoalPeriod;
}

// Фильтры для списка целей
export interface SKUGoalsFilter {
    categoryId?: Category;
    skuClass?: SKUClass;
    status?: 'exceeds' | 'on_track' | 'at_risk' | 'behind';
    search?: string;
    period: GoalPeriod;
}

// Статистика по целям
export interface SKUGoalsStats {
    total: number;
    byClass: Record<SKUClass, number>;
    byStatus: {
        exceeds: number;
        onTrack: number;
        atRisk: number;
        behind: number;
    };
    avgProgress: {
        ctr: number;
        crCart: number;
        crOrder: number;
    };
}

// Утилиты

// Рассчитать статус прогресса
export function calculateGoalStatus(progress: number): 'exceeds' | 'on_track' | 'at_risk' | 'behind' {
    if (progress >= 100) return 'exceeds';
    if (progress >= 80) return 'on_track';
    if (progress >= 50) return 'at_risk';
    return 'behind';
}

// Получить общий статус SKU по всем метрикам
export function getSKUOverallStatus(
    ctrProgress: number,
    crCartProgress: number,
    crOrderProgress: number
): { status: 'exceeds' | 'on_track' | 'at_risk' | 'behind'; issueCount: number } {
    const progressValues = [ctrProgress, crCartProgress, crOrderProgress];
    const issueCount = progressValues.filter(p => p < 80).length;

    if (issueCount === 0 && progressValues.every(p => p >= 100)) {
        return { status: 'exceeds', issueCount: 0 };
    }
    if (issueCount === 0) {
        return { status: 'on_track', issueCount: 0 };
    }
    if (issueCount <= 1) {
        return { status: 'at_risk', issueCount };
    }
    return { status: 'behind', issueCount };
}

// Цвета статусов
export const GOAL_STATUS_STYLES: Record<string, { bg: string; text: string; icon: string }> = {
    exceeds: { bg: 'bg-green-500/20', text: 'text-green-400', icon: '🚀' },
    on_track: { bg: 'bg-blue-500/20', text: 'text-blue-400', icon: '✓' },
    at_risk: { bg: 'bg-yellow-500/20', text: 'text-yellow-400', icon: '⚠️' },
    behind: { bg: 'bg-red-500/20', text: 'text-red-400', icon: '❌' },
};
